spring:
#  h2:
#    console:
#      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:mysql://springboot-database.cuembkmhoi0a.ap-northeast-2.rds.amazonaws.com:3306/myselectshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: iy719412

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    com.tutorial: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwtZG93b29uCg==

cloud:
  aws:
    credentials:
      accessKey: AKIARC436G6RAZUTUY5M # AWS IAM AccessKey 적기
      secretKey: FEBz7jX6Z2qAd6hoX6u9SxJbGiZw5dAised0DK9K # AWS IAM SecretKey 적기
    s3:
      bucket: miniproject-spring # ex) marryting-gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8000
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 719412

