spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  h2:
#    console:
#      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: 
    driver-class-name: 
    username: 
    password:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    com.tutorial: 

jwt:
  secret:

cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket:
    region:
      static:
    stack:
      auto:

server:
  port: 8000
  ssl:
    enabled:
    key-store:
    key-store-type: 
    key-store-password: 

